# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RNCouchbaseLiteReactNativeModuleIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNCouchbaseLiteReactNativeModuleIos

 #pod 'CouchbaseLite-Swift', '~> 2.7.0'

end
