export declare function multiply(a: number, b: number): Promise<number>;
export declare function CreateOrOpenDatabase(dbname: string, config: Object, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function closeDatabase(dbname: string, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function deleteDatabase(dbname: string): Promise<string>;
export declare function copyDatabase(currentdbname: string, newDBName: string, currentConfig: Object, newConfig: Object, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function databaseExists(dbname: string, config: Object): Promise<string>;
export declare function deleteDocument(dbname: string, docid: string, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function getDocument(dbname: string, docid: string, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function setDocument(dbname: string, docid: string, data: string, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function setBlob(dbname: string, type: string, docObject: string, key: string, config: Object): Promise<string>;
export declare function createValueIndex(dbname: string, indexName: string, indexExpressions: [string]): Promise<string>;
export declare function createFTSIndex(dbname: string, indexName: string, options:Object, indexExpressions: [string]): Promise<string>;
export declare function deleteIndex(dbname: string, indexName: string): Promise<string>;
export declare function addDatabaseChangeListener(dbname: string, listener: string): Promise<string>;
export declare function removeDatabaseChangeListener(dbname: string): Promise<string>;
export declare function enableConsoleLogging(domain: string, logLevel: string): Promise<string>;
export declare function createQuery(dbname: string, query: string): Promise<string>;
export declare function query(dbname: string, query: string, OnSuccessCallback: Function, OnErrorCallback: Function): void;
export declare function queryWithChangeListener(dbname: string, query: string, listener: string): Promise<string>;
export declare function removeQueryChangeListener(dbname: string, query: string): Promise<string>;
